#Eduardo Ramos
### GET method - list all
GET http://localhost:8000/produto/ HTTP/1.1

### GET method - list one
GET http://localhost:8000/produto/10 HTTP/1.1

### POST method - add one
POST http://localhost:8000/produto/ HTTP/1.1

### PUT method - edit one
PUT http://localhost:8000/produto/2 HTTP/1.1

### DELETE method - remove one
DELETE http://localhost:8000/produto/3 HTTP/1.1