#Eduardo Ramos
### GET method - list all
GET http://localhost:8000/funcionario/ HTTP/1.1

### GET method - list one
GET http://localhost:8000/funcionario/10 HTTP/1.1

### POST method - add one
POST http://localhost:8000/funcionario/ HTTP/1.1    
Content-Type: application/json

{
    "nome" : "Eduardo Ramos",
    "matricula" : "150912",
    "cpf" : "01247366960",
    "telefone" : "49999516632",
    "grupo" : 1,
    "senha" : "ramos4123"
}

### PUT method - edit one
PUT http://localhost:8000/funcionario/2 HTTP/1.1

### DELETE method - remove one
DELETE http://localhost:8000/funcionario/3 HTTP/1.1